markdown: kramdown
redcarpet:
 extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: false

# Dependencies
kramdown:
  input: GFM   #Github Flavored Markdown

# Permalinks
permalink:        pretty

# Setup
title:            Hyperstore
url:              http://www.hyperstore.org
paginate:         1
baseurl:          /
author:
  name:           Alain Metge
  url:            https://twitter.com/hyperstore
  email:          alain.metge@zenasoft.com

#readthedocs config
#repo_url: https://github.
homepage_url: /

# Custom vars
version:          1.0.0
github_url:       https://github.com/hyperstore.doc

docs:
- ['/index.html', 'Home', 'Hyperstore documentation']
- ['/GettingStarted/Overview/', 'Getting started', 'Hyperstore overview']
- ['/GettingStarted/Overview/', 'Getting started', 'Concepts']
- ['/GettingStarted/Overview/', 'Getting started', 'Architecture']
- ['/GettingStarted/Overview/', 'Getting started', 'Schema']
- ['/GettingStarted/Overview/', 'Getting started', 'Store and domain']
- ['/GettingStarted/Overview/', 'Getting started', 'Session']
- ['/GettingStarted/Overview/', 'Getting started', 'Events']
- ['/GettingStarted/Overview/', 'Getting started', 'Constraints']
- ['/GettingStarted/Overview/', 'Getting started', 'Commands']
- ['/DomainLanguage/Introduction/', 'Domain Language', 'Introduction']
- ['/DomainLanguage/Domain/', 'Domain Language', 'Domain']
- ['/DomainLanguage/Usings/', 'Domain Language', 'Using']
- ['/DomainLanguage/Externals/', 'Domain Language', 'Externals']
- ['/DomainLanguage/Entities/', 'Domain Language', 'Entities']
- ['/DomainLanguage/Relationships/', 'Domain Language', 'Relationships']
- ['/DomainLanguage/Enums/', 'Domain Language', 'Enums']
- ['/DomainLanguage/Properties/', 'Domain Language', 'Properties']
- ['/DomainLanguage/References/', 'Domain Language', 'References']
- ['/DomainLanguage/ValueObjects/', 'Domain Language', 'ValueObjects']
- ['/DomainLanguage/SyntaxReference/', 'Domain Language', 'Language reference']
- ['/Samples/Overview/', 'Samples', 'Observable domain']
- ['/About/', 'About', 'About']