markdown: redcarpet
redcarpet:
 extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: true

# Dependencies
kramdown:
  input: GFM   #Github Flavored Markdown

# Permalinks
permalink:        pretty

# Setup
title:            Hyperstore documentation
url:              http://doc.hyperstore.org
paginate:         1
baseurl:          /
author:
  name:           Alain Metge
  url:            https://twitter.com/hyperstore
  email:          alain.metge@zenasoft.com

#readthedocs config
#repo_url: https://github.
homepage_url: /

# Custom vars
version:          1.0.0
github_url:       https://github.com/hyperstore.doc

docs:
- ['index.html', 'Home', 'Home']
- ['GettingStarted/CreateAnObservableDomain', 'Getting started', 'Create an observable domain']
- ['DomainLanguage/Introduction', 'Domain Language', 'Introduction']
- ['DomainLanguage/Domain', 'Domain Language', 'Domain']
- ['DomainLanguage/Usings', 'Domain Language', 'Using']
- ['DomainLanguage/Externals', 'Domain Language', 'Externals']
- ['DomainLanguage/Entities', 'Domain Language', 'Entties']
- ['DomainLanguage/Relationships', 'Domain Language', 'Relationships']
- ['DomainLanguage/Enums', 'Domain Language', 'Enums']
- ['DomainLanguage/Properties', 'Domain Language', 'Properties']
- ['DomainLanguage/References', 'Domain Language', 'References']
- ['DomainLanguage/ValueObjects', 'Domain Language', 'ValueObjects']
- ['DomainLanguage/SyntaxReference', 'Domain Language', 'Reference']
- ['Samples/Overview', 'Samples', 'Observable domain']
- ['About', 'About', 'About']